version: '3'
services:
  web:
    build: .
    depends_on:
      - 'selenium'
    command: ['/app/wait-for-selenium.sh', 'http://selenium:4444/wd/hub', '--', 'python', '/app/start.py']
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome
    shm_size: 128M
