version: '3'
services:
  web:
    command: python /app/start.py
    environment:
      - PYTHONUNBUFFERED=0
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - selenium
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "5900:5900"
    shm_size: 128M
