version: '3'
services:
  web:
    build: .
    depends_on:
      - 'selenium'
    command: ['/app/wait-for-selenium.sh', '${URL_SELENIUM_HUB}', '--', 'python', '/app/start.py']
    env_file:
      - .env
  selenium:
    container_name: ${HOSTNAME}
    image: selenium/standalone-chrome
    shm_size: 128M
