version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - selenium
    command: 'python /app/start.py'
  selenium:
    image: selenium/standalone-chrome
    ports:
      - '5900:5900'
    shm_size: 128M
