version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - selenium
    command: 'python /app/start.py'
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome
    shm_size: 128M
